// Generates a static HTML page comparing baseline vs current screenshots.
// Usage: npx tsx scripts/build-screenshot-review.ts
//
// Reads PNGs from screenshots/baseline/ and screenshots/, generates
// guides/design/screenshot-review.html with side-by-side image pairs.

import { existsSync, readdirSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const baselineDir = path.join(root, 'screenshots', 'baseline');
const currentDir = path.join(root, 'screenshots');
const outputFile = path.join(
  root,
  'guides',
  'design',
  'screenshot-review.html',
);

if (!existsSync(baselineDir)) {
  console.error(
    'No baseline screenshots found.\n' +
      'Run: npx tsx scripts/take-screenshots.ts --dir screenshots/baseline',
  );
  process.exit(1);
}

const baselineFiles = readdirSync(baselineDir)
  .filter((f) => f.endsWith('.png'))
  .sort();
const currentFiles = readdirSync(currentDir)
  .filter((f) => f.endsWith('.png'))
  .sort();
const allNames = [...new Set([...baselineFiles, ...currentFiles])].sort();

if (allNames.length === 0) {
  console.error('No screenshots found in either directory.');
  process.exit(1);
}

let pairs = '';
for (const name of allNames) {
  const hasBaseline = baselineFiles.includes(name);
  const hasCurrent = currentFiles.includes(name);
  const label = name.replace('.png', '');

  const baseImg = hasBaseline
    ? `<img src="../../screenshots/baseline/${name}" alt="baseline" loading="lazy">`
    : '<div class="missing">No baseline</div>';
  const curImg = hasCurrent
    ? `<img src="../../screenshots/${name}" alt="current" loading="lazy">`
    : '<div class="missing">No current</div>';

  pairs += `
  <div class="pair">
    <h3>${label}</h3>
    <div class="images">
      <div class="img-col"><div class="img-label">Baseline</div>${baseImg}</div>
      <div class="img-col"><div class="img-label">Current</div>${curImg}</div>
    </div>
  </div>`;
}

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Screenshot Review &mdash; Music Reps</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem 1rem;
      background: #f5f5f5;
      color: #333;
    }
    h1 { font-size: 1.5rem; margin: 0 0 0.25rem; }
    .subtitle { color: #888; font-size: 0.9rem; margin-bottom: 2rem; }
    h3 {
      font-size: 0.9rem;
      margin: 2rem 0 0.5rem;
      padding-bottom: 0.25rem;
      border-bottom: 1px solid #ddd;
    }
    .images { display: flex; gap: 1rem; flex-wrap: wrap; }
    .img-col { flex: 1; min-width: 300px; }
    .img-label {
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      color: #888;
      margin-bottom: 0.25rem;
    }
    img {
      width: 100%;
      border: 1px solid #ddd;
      border-radius: 4px;
      background: white;
    }
    .missing {
      padding: 2rem;
      text-align: center;
      color: #999;
      border: 2px dashed #ddd;
      border-radius: 4px;
    }
  </style>
</head>
<body>
  <h1>Screenshot Review</h1>
  <div class="subtitle">
    Baseline vs current screenshots &mdash; ${allNames.length} pairs.
    Generated by <code>scripts/build-screenshot-review.ts</code>.
  </div>
${pairs}
</body>
</html>`;

writeFileSync(outputFile, html);
console.log(
  `Review page: ${path.relative(root, outputFile)} (${allNames.length} pairs)`,
);
